### ISSUE TITLE
after using enable its shows this error

### ISSUE THREAD

**Issue by ItsToxicGG** [BlckqPlugins/SkyWars#2]
## Name
after using enable 

### Description:

[16:13:30.582] [Server thread/CRITICAL]: pocketmine\utils\AssumptionFailedError: "Position world is null or has been unloaded" (EXCEPTION) in "pmsrc/src/world/Position" at line 70
--- Stack trace ---
  #0 plugins/SkyWars/src/vixikhd/skywars/arena/ArenaScheduler(137): pocketmine\world\Position->getWorld()
  #1 plugins/SkyWars/src/vixikhd/skywars/arena/ArenaScheduler(63): vixikhd\skywars\arena\ArenaScheduler->reloadSign()
  #2 pmsrc/src/scheduler/TaskHandler(117): vixikhd\skywars\arena\ArenaScheduler->onRun()
  #3 pmsrc/src/scheduler/TaskScheduler(141): pocketmine\scheduler\TaskHandler->run()
  #4 pmsrc/src/plugin/PluginManager(466): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 1)
  #5 pmsrc/src/Server(1774): pocketmine\plugin\PluginManager->tickSchedulers(integer 1)
  #6 pmsrc/src/Server(1663): pocketmine\Server->tick()
  #7 pmsrc/src/Server(1051): pocketmine\Server->tickProcessor()
  #8 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[37] C:\Users\User\OneDrive\Desktop\Flana\, string[45] C:\Users\User\OneDrive\Desktop\Flana\plugins\)
  #9 pmsrc/src/PocketMine(327): pocketmine\server()
  #10 pmsrc(11): require(string[81] phar://C:/Users/User/OneDrive/Desktop/Flana/PocketMine-MP.phar/src/PocketMine.ph)
--- End of exception information ---
[16:13:30.583] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[16:13:30.622] [Server thread/EMERGENCY]: Please upload the "C:/Users/User/OneDrive/Desktop/Flana/crashdumps/Fri_Mar_4-16.13.30-GMT_2022.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
[16:13:30.638] [Server thread/EMERGENCY]: Forcing server shutdown

### How to reproduce?

1) ...
2) ...

### Server version:

- This server is running ... 「...」 implementing API version ... for Minecraft: ... ... (protocol version ...)

**Comment by Smorted** [comment]
did you manage to fix it?

**Comment by xxFLORII** [comment]
> did you manage to fix it?

i will fix it asap

**Comment by Smorted** [comment]
looking forward to seeing it

**Comment by Smorted** [comment]
any updates? im depending on this plugin for my server

**Comment by Smorted** [comment]
this will fix the issue, tho can u implement a join command with random arena select? just like in gamacz's 1vs1 plugin  (which can be found in his repos)
